/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.is2300.jedi.edi.gui;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.is2300.jedi.edi.gui//AuditExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "AuditExplorerTopComponent",
        //iconBase = "/set/path/here",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "com.is2300.jedi.edi.gui.AuditExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_AuditExplorerAction",
        preferredID = "AuditExplorerTopComponent"
)
@Messages({
    "CTL_AuditExplorerAction=Audits Explorer",
    "CTL_AuditExplorerTopComponent=Audits Explorer",
    "HINT_AuditExplorerTopComponent=This is a Audits Explorer"
})
public final class AuditExplorerTopComponent extends TopComponent {

    public AuditExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_AuditExplorerTopComponent());
        setToolTipText(Bundle.HINT_AuditExplorerTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        auditSelector = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Audits");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("2013");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("2014");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("2015");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("2016");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("2017");
        treeNode1.add(treeNode2);
        auditSelector.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        auditSelector.setRootVisible(false);
        auditSelector.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                auditSelectorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(auditSelector);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void auditSelectorValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_auditSelectorValueChanged
        // When a node is selected, we need to show that node's data in the
        //+ AuditViewer window.
        AuditViewerTopComponent av = new AuditViewerTopComponent();
        av.setVisible(true);
    }//GEN-LAST:event_auditSelectorValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree auditSelector;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
